# Generated by Django 3.2.8 on 2022-02-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap', '0002_route_waypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(default='a route', max_length=100),
            preserve_default=False,
        ),
    ]
